// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feedback.proto

package feedback

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PassengerFeedback struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	PassengerID          int32    `protobuf:"varint,2,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	Feedback             string   `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerFeedback) Reset()         { *m = PassengerFeedback{} }
func (m *PassengerFeedback) String() string { return proto.CompactTextString(m) }
func (*PassengerFeedback) ProtoMessage()    {}
func (*PassengerFeedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{0}
}

func (m *PassengerFeedback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerFeedback.Unmarshal(m, b)
}
func (m *PassengerFeedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerFeedback.Marshal(b, m, deterministic)
}
func (m *PassengerFeedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerFeedback.Merge(m, src)
}
func (m *PassengerFeedback) XXX_Size() int {
	return xxx_messageInfo_PassengerFeedback.Size(m)
}
func (m *PassengerFeedback) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerFeedback.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerFeedback proto.InternalMessageInfo

func (m *PassengerFeedback) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

func (m *PassengerFeedback) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

func (m *PassengerFeedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

type AddCustomerFeedbackRequest struct {
	Feedback             *PassengerFeedback `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AddCustomerFeedbackRequest) Reset()         { *m = AddCustomerFeedbackRequest{} }
func (m *AddCustomerFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*AddCustomerFeedbackRequest) ProtoMessage()    {}
func (*AddCustomerFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{1}
}

func (m *AddCustomerFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCustomerFeedbackRequest.Unmarshal(m, b)
}
func (m *AddCustomerFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCustomerFeedbackRequest.Marshal(b, m, deterministic)
}
func (m *AddCustomerFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCustomerFeedbackRequest.Merge(m, src)
}
func (m *AddCustomerFeedbackRequest) XXX_Size() int {
	return xxx_messageInfo_AddCustomerFeedbackRequest.Size(m)
}
func (m *AddCustomerFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCustomerFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCustomerFeedbackRequest proto.InternalMessageInfo

func (m *AddCustomerFeedbackRequest) GetFeedback() *PassengerFeedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type AddCustomerFeedbackResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCustomerFeedbackResponse) Reset()         { *m = AddCustomerFeedbackResponse{} }
func (m *AddCustomerFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*AddCustomerFeedbackResponse) ProtoMessage()    {}
func (*AddCustomerFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{2}
}

func (m *AddCustomerFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCustomerFeedbackResponse.Unmarshal(m, b)
}
func (m *AddCustomerFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCustomerFeedbackResponse.Marshal(b, m, deterministic)
}
func (m *AddCustomerFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCustomerFeedbackResponse.Merge(m, src)
}
func (m *AddCustomerFeedbackResponse) XXX_Size() int {
	return xxx_messageInfo_AddCustomerFeedbackResponse.Size(m)
}
func (m *AddCustomerFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCustomerFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCustomerFeedbackResponse proto.InternalMessageInfo

func (m *AddCustomerFeedbackResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetFeedbacksByPassengerIdRequest struct {
	PassengerID          int32    `protobuf:"varint,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedbacksByPassengerIdRequest) Reset()         { *m = GetFeedbacksByPassengerIdRequest{} }
func (m *GetFeedbacksByPassengerIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedbacksByPassengerIdRequest) ProtoMessage()    {}
func (*GetFeedbacksByPassengerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{3}
}

func (m *GetFeedbacksByPassengerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbacksByPassengerIdRequest.Unmarshal(m, b)
}
func (m *GetFeedbacksByPassengerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbacksByPassengerIdRequest.Marshal(b, m, deterministic)
}
func (m *GetFeedbacksByPassengerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbacksByPassengerIdRequest.Merge(m, src)
}
func (m *GetFeedbacksByPassengerIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedbacksByPassengerIdRequest.Size(m)
}
func (m *GetFeedbacksByPassengerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbacksByPassengerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbacksByPassengerIdRequest proto.InternalMessageInfo

func (m *GetFeedbacksByPassengerIdRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type GetFeedbacksByPassengerIdResponse struct {
	Feedbacks            []*PassengerFeedback `protobuf:"bytes,1,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetFeedbacksByPassengerIdResponse) Reset()         { *m = GetFeedbacksByPassengerIdResponse{} }
func (m *GetFeedbacksByPassengerIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedbacksByPassengerIdResponse) ProtoMessage()    {}
func (*GetFeedbacksByPassengerIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{4}
}

func (m *GetFeedbacksByPassengerIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbacksByPassengerIdResponse.Unmarshal(m, b)
}
func (m *GetFeedbacksByPassengerIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbacksByPassengerIdResponse.Marshal(b, m, deterministic)
}
func (m *GetFeedbacksByPassengerIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbacksByPassengerIdResponse.Merge(m, src)
}
func (m *GetFeedbacksByPassengerIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedbacksByPassengerIdResponse.Size(m)
}
func (m *GetFeedbacksByPassengerIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbacksByPassengerIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbacksByPassengerIdResponse proto.InternalMessageInfo

func (m *GetFeedbacksByPassengerIdResponse) GetFeedbacks() []*PassengerFeedback {
	if m != nil {
		return m.Feedbacks
	}
	return nil
}

type GetFeedbackByBookingCodeRequest struct {
	BookingCode          string   `protobuf:"bytes,1,opt,name=bookingCode,proto3" json:"bookingCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFeedbackByBookingCodeRequest) Reset()         { *m = GetFeedbackByBookingCodeRequest{} }
func (m *GetFeedbackByBookingCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackByBookingCodeRequest) ProtoMessage()    {}
func (*GetFeedbackByBookingCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{5}
}

func (m *GetFeedbackByBookingCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackByBookingCodeRequest.Unmarshal(m, b)
}
func (m *GetFeedbackByBookingCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackByBookingCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetFeedbackByBookingCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackByBookingCodeRequest.Merge(m, src)
}
func (m *GetFeedbackByBookingCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackByBookingCodeRequest.Size(m)
}
func (m *GetFeedbackByBookingCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackByBookingCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackByBookingCodeRequest proto.InternalMessageInfo

func (m *GetFeedbackByBookingCodeRequest) GetBookingCode() string {
	if m != nil {
		return m.BookingCode
	}
	return ""
}

type GetFeedbackByBookingCodeResponse struct {
	Feedback             *PassengerFeedback `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetFeedbackByBookingCodeResponse) Reset()         { *m = GetFeedbackByBookingCodeResponse{} }
func (m *GetFeedbackByBookingCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetFeedbackByBookingCodeResponse) ProtoMessage()    {}
func (*GetFeedbackByBookingCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{6}
}

func (m *GetFeedbackByBookingCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFeedbackByBookingCodeResponse.Unmarshal(m, b)
}
func (m *GetFeedbackByBookingCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFeedbackByBookingCodeResponse.Marshal(b, m, deterministic)
}
func (m *GetFeedbackByBookingCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFeedbackByBookingCodeResponse.Merge(m, src)
}
func (m *GetFeedbackByBookingCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetFeedbackByBookingCodeResponse.Size(m)
}
func (m *GetFeedbackByBookingCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFeedbackByBookingCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFeedbackByBookingCodeResponse proto.InternalMessageInfo

func (m *GetFeedbackByBookingCodeResponse) GetFeedback() *PassengerFeedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type DeleteFeedbacksByPassengerIdRequest struct {
	PassengerID          int32    `protobuf:"varint,1,opt,name=passengerID,proto3" json:"passengerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFeedbacksByPassengerIdRequest) Reset()         { *m = DeleteFeedbacksByPassengerIdRequest{} }
func (m *DeleteFeedbacksByPassengerIdRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFeedbacksByPassengerIdRequest) ProtoMessage()    {}
func (*DeleteFeedbacksByPassengerIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{7}
}

func (m *DeleteFeedbacksByPassengerIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeedbacksByPassengerIdRequest.Unmarshal(m, b)
}
func (m *DeleteFeedbacksByPassengerIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeedbacksByPassengerIdRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFeedbacksByPassengerIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeedbacksByPassengerIdRequest.Merge(m, src)
}
func (m *DeleteFeedbacksByPassengerIdRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFeedbacksByPassengerIdRequest.Size(m)
}
func (m *DeleteFeedbacksByPassengerIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeedbacksByPassengerIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeedbacksByPassengerIdRequest proto.InternalMessageInfo

func (m *DeleteFeedbacksByPassengerIdRequest) GetPassengerID() int32 {
	if m != nil {
		return m.PassengerID
	}
	return 0
}

type DeleteFeedbacksByPassengerIdResponse struct {
	DeletedFeedbacks     int32    `protobuf:"varint,1,opt,name=deletedFeedbacks,proto3" json:"deletedFeedbacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFeedbacksByPassengerIdResponse) Reset()         { *m = DeleteFeedbacksByPassengerIdResponse{} }
func (m *DeleteFeedbacksByPassengerIdResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFeedbacksByPassengerIdResponse) ProtoMessage()    {}
func (*DeleteFeedbacksByPassengerIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b189e8c8330c03e, []int{8}
}

func (m *DeleteFeedbacksByPassengerIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFeedbacksByPassengerIdResponse.Unmarshal(m, b)
}
func (m *DeleteFeedbacksByPassengerIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFeedbacksByPassengerIdResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFeedbacksByPassengerIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFeedbacksByPassengerIdResponse.Merge(m, src)
}
func (m *DeleteFeedbacksByPassengerIdResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFeedbacksByPassengerIdResponse.Size(m)
}
func (m *DeleteFeedbacksByPassengerIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFeedbacksByPassengerIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFeedbacksByPassengerIdResponse proto.InternalMessageInfo

func (m *DeleteFeedbacksByPassengerIdResponse) GetDeletedFeedbacks() int32 {
	if m != nil {
		return m.DeletedFeedbacks
	}
	return 0
}

func init() {
	proto.RegisterType((*PassengerFeedback)(nil), "feedback.PassengerFeedback")
	proto.RegisterType((*AddCustomerFeedbackRequest)(nil), "feedback.AddCustomerFeedbackRequest")
	proto.RegisterType((*AddCustomerFeedbackResponse)(nil), "feedback.AddCustomerFeedbackResponse")
	proto.RegisterType((*GetFeedbacksByPassengerIdRequest)(nil), "feedback.GetFeedbacksByPassengerIdRequest")
	proto.RegisterType((*GetFeedbacksByPassengerIdResponse)(nil), "feedback.GetFeedbacksByPassengerIdResponse")
	proto.RegisterType((*GetFeedbackByBookingCodeRequest)(nil), "feedback.GetFeedbackByBookingCodeRequest")
	proto.RegisterType((*GetFeedbackByBookingCodeResponse)(nil), "feedback.GetFeedbackByBookingCodeResponse")
	proto.RegisterType((*DeleteFeedbacksByPassengerIdRequest)(nil), "feedback.DeleteFeedbacksByPassengerIdRequest")
	proto.RegisterType((*DeleteFeedbacksByPassengerIdResponse)(nil), "feedback.DeleteFeedbacksByPassengerIdResponse")
}

func init() { proto.RegisterFile("feedback.proto", fileDescriptor_7b189e8c8330c03e) }

var fileDescriptor_7b189e8c8330c03e = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x4b, 0x32, 0x41,
	0x14, 0x7e, 0xf7, 0x5d, 0x8a, 0x3c, 0x42, 0xd8, 0x74, 0xb3, 0x8d, 0x41, 0xdb, 0x64, 0x60, 0x46,
	0x06, 0x76, 0x11, 0x5d, 0xa6, 0x8b, 0xe2, 0x5d, 0x2c, 0x74, 0x15, 0x04, 0xda, 0x9c, 0x24, 0x4c,
	0xc7, 0x9c, 0x35, 0xf0, 0xaa, 0x7f, 0xdb, 0xef, 0x88, 0xb5, 0x9d, 0x9d, 0x49, 0xf7, 0x8b, 0xba,
	0xd3, 0xc3, 0x33, 0xcf, 0xc7, 0x39, 0x0f, 0x0b, 0xbb, 0xcf, 0x88, 0x7c, 0x38, 0x78, 0x1a, 0x37,
	0x67, 0x73, 0x11, 0x08, 0xb2, 0xa3, 0xfe, 0x33, 0x09, 0x7b, 0x77, 0x03, 0x29, 0x71, 0x3a, 0xc2,
	0x79, 0x37, 0x1a, 0x12, 0x17, 0xca, 0x43, 0x21, 0xc6, 0x2f, 0xd3, 0x51, 0x47, 0x70, 0x74, 0x2c,
	0xd7, 0xaa, 0x97, 0x7c, 0x73, 0x14, 0x22, 0x66, 0xea, 0x59, 0xdf, 0x73, 0xfe, 0xbb, 0x56, 0x7d,
	0xcb, 0x37, 0x47, 0x84, 0x42, 0x2c, 0xe2, 0xd8, 0x2b, 0x02, 0x2d, 0x7a, 0x0f, 0xf4, 0x96, 0xf3,
	0xce, 0x42, 0x06, 0x62, 0xa2, 0x65, 0x7d, 0x7c, 0x5b, 0xa0, 0x0c, 0xc8, 0xb5, 0xf1, 0x32, 0x94,
	0x2e, 0xb7, 0xaa, 0xcd, 0xd8, 0xff, 0x86, 0x59, 0x83, 0xf6, 0x12, 0xaa, 0x89, 0xb4, 0x72, 0x26,
	0xa6, 0x12, 0x49, 0x05, 0xec, 0x89, 0x1c, 0x45, 0x69, 0xc2, 0x9f, 0xcc, 0x03, 0xb7, 0x87, 0x81,
	0x02, 0xca, 0xf6, 0x32, 0x66, 0xef, 0x73, 0xe5, 0x66, 0x2d, 0xa9, 0xb5, 0x91, 0x94, 0x3d, 0xc2,
	0x71, 0x06, 0x4b, 0x24, 0x7e, 0x03, 0x25, 0xe5, 0x53, 0x3a, 0x96, 0x6b, 0xe7, 0xa5, 0xd2, 0x68,
	0xd6, 0x81, 0x23, 0x83, 0xbf, 0xbd, 0x6c, 0xeb, 0x3b, 0x18, 0x26, 0xb3, 0x0f, 0xc6, 0x1e, 0x7e,
	0x44, 0x5d, 0x23, 0x89, 0x3c, 0xfe, 0x7a, 0xf1, 0x3d, 0x38, 0xf1, 0xf0, 0x15, 0x03, 0xfc, 0xeb,
	0x2a, 0x7d, 0xa8, 0x65, 0x13, 0x45, 0x4e, 0x1b, 0x50, 0xe1, 0x2b, 0x1c, 0xef, 0x1a, 0x4b, 0x0d,
	0xe9, 0x36, 0xe6, 0xad, 0x4f, 0x1b, 0x2a, 0xeb, 0x9d, 0x20, 0x1c, 0xf6, 0x13, 0xaa, 0x42, 0x6a,
	0x3a, 0x6f, 0x7a, 0x41, 0xe9, 0x69, 0x0e, 0xea, 0xdb, 0x24, 0xfb, 0x47, 0xde, 0xe1, 0x20, 0xad,
	0x19, 0x1e, 0x69, 0x68, 0x96, 0xbc, 0x12, 0xd2, 0xf3, 0x42, 0xd8, 0x58, 0x57, 0x82, 0x93, 0x76,
	0x6c, 0x72, 0x96, 0x48, 0x95, 0xd4, 0x2a, 0xda, 0x28, 0x02, 0x8d, 0x45, 0x3f, 0xe0, 0x30, 0xe3,
	0x76, 0x1e, 0xb9, 0xd0, 0x6c, 0x05, 0xca, 0x42, 0x9b, 0x45, 0xe1, 0xca, 0xc0, 0x70, 0x7b, 0xf5,
	0x6d, 0xbb, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x4f, 0x1c, 0x7c, 0xed, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerFeedbackClient is the client API for CustomerFeedback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerFeedbackClient interface {
	// Add a customer feedback
	AddCustomerFeedback(ctx context.Context, in *AddCustomerFeedbackRequest, opts ...grpc.CallOption) (*AddCustomerFeedbackResponse, error)
	// Get feedback by passengerID
	GetFeedbacksByPassengerID(ctx context.Context, in *GetFeedbacksByPassengerIdRequest, opts ...grpc.CallOption) (*GetFeedbacksByPassengerIdResponse, error)
	// Get feedback by booking code
	GetFeedbackByBookingCode(ctx context.Context, in *GetFeedbackByBookingCodeRequest, opts ...grpc.CallOption) (*GetFeedbackByBookingCodeResponse, error)
	// Delete feedbacks by passengerID
	DeleteFeedbacksByPassengerID(ctx context.Context, in *DeleteFeedbacksByPassengerIdRequest, opts ...grpc.CallOption) (*DeleteFeedbacksByPassengerIdResponse, error)
}

type customerFeedbackClient struct {
	cc *grpc.ClientConn
}

func NewCustomerFeedbackClient(cc *grpc.ClientConn) CustomerFeedbackClient {
	return &customerFeedbackClient{cc}
}

func (c *customerFeedbackClient) AddCustomerFeedback(ctx context.Context, in *AddCustomerFeedbackRequest, opts ...grpc.CallOption) (*AddCustomerFeedbackResponse, error) {
	out := new(AddCustomerFeedbackResponse)
	err := c.cc.Invoke(ctx, "/feedback.CustomerFeedback/AddCustomerFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerFeedbackClient) GetFeedbacksByPassengerID(ctx context.Context, in *GetFeedbacksByPassengerIdRequest, opts ...grpc.CallOption) (*GetFeedbacksByPassengerIdResponse, error) {
	out := new(GetFeedbacksByPassengerIdResponse)
	err := c.cc.Invoke(ctx, "/feedback.CustomerFeedback/GetFeedbacksByPassengerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerFeedbackClient) GetFeedbackByBookingCode(ctx context.Context, in *GetFeedbackByBookingCodeRequest, opts ...grpc.CallOption) (*GetFeedbackByBookingCodeResponse, error) {
	out := new(GetFeedbackByBookingCodeResponse)
	err := c.cc.Invoke(ctx, "/feedback.CustomerFeedback/GetFeedbackByBookingCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerFeedbackClient) DeleteFeedbacksByPassengerID(ctx context.Context, in *DeleteFeedbacksByPassengerIdRequest, opts ...grpc.CallOption) (*DeleteFeedbacksByPassengerIdResponse, error) {
	out := new(DeleteFeedbacksByPassengerIdResponse)
	err := c.cc.Invoke(ctx, "/feedback.CustomerFeedback/DeleteFeedbacksByPassengerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerFeedbackServer is the server API for CustomerFeedback service.
type CustomerFeedbackServer interface {
	// Add a customer feedback
	AddCustomerFeedback(context.Context, *AddCustomerFeedbackRequest) (*AddCustomerFeedbackResponse, error)
	// Get feedback by passengerID
	GetFeedbacksByPassengerID(context.Context, *GetFeedbacksByPassengerIdRequest) (*GetFeedbacksByPassengerIdResponse, error)
	// Get feedback by booking code
	GetFeedbackByBookingCode(context.Context, *GetFeedbackByBookingCodeRequest) (*GetFeedbackByBookingCodeResponse, error)
	// Delete feedbacks by passengerID
	DeleteFeedbacksByPassengerID(context.Context, *DeleteFeedbacksByPassengerIdRequest) (*DeleteFeedbacksByPassengerIdResponse, error)
}

// UnimplementedCustomerFeedbackServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerFeedbackServer struct {
}

func (*UnimplementedCustomerFeedbackServer) AddCustomerFeedback(ctx context.Context, req *AddCustomerFeedbackRequest) (*AddCustomerFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCustomerFeedback not implemented")
}
func (*UnimplementedCustomerFeedbackServer) GetFeedbacksByPassengerID(ctx context.Context, req *GetFeedbacksByPassengerIdRequest) (*GetFeedbacksByPassengerIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbacksByPassengerID not implemented")
}
func (*UnimplementedCustomerFeedbackServer) GetFeedbackByBookingCode(ctx context.Context, req *GetFeedbackByBookingCodeRequest) (*GetFeedbackByBookingCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeedbackByBookingCode not implemented")
}
func (*UnimplementedCustomerFeedbackServer) DeleteFeedbacksByPassengerID(ctx context.Context, req *DeleteFeedbacksByPassengerIdRequest) (*DeleteFeedbacksByPassengerIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFeedbacksByPassengerID not implemented")
}

func RegisterCustomerFeedbackServer(s *grpc.Server, srv CustomerFeedbackServer) {
	s.RegisterService(&_CustomerFeedback_serviceDesc, srv)
}

func _CustomerFeedback_AddCustomerFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCustomerFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerFeedbackServer).AddCustomerFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.CustomerFeedback/AddCustomerFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerFeedbackServer).AddCustomerFeedback(ctx, req.(*AddCustomerFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerFeedback_GetFeedbacksByPassengerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbacksByPassengerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerFeedbackServer).GetFeedbacksByPassengerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.CustomerFeedback/GetFeedbacksByPassengerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerFeedbackServer).GetFeedbacksByPassengerID(ctx, req.(*GetFeedbacksByPassengerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerFeedback_GetFeedbackByBookingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackByBookingCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerFeedbackServer).GetFeedbackByBookingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.CustomerFeedback/GetFeedbackByBookingCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerFeedbackServer).GetFeedbackByBookingCode(ctx, req.(*GetFeedbackByBookingCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerFeedback_DeleteFeedbacksByPassengerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeedbacksByPassengerIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerFeedbackServer).DeleteFeedbacksByPassengerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedback.CustomerFeedback/DeleteFeedbacksByPassengerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerFeedbackServer).DeleteFeedbacksByPassengerID(ctx, req.(*DeleteFeedbacksByPassengerIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerFeedback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feedback.CustomerFeedback",
	HandlerType: (*CustomerFeedbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCustomerFeedback",
			Handler:    _CustomerFeedback_AddCustomerFeedback_Handler,
		},
		{
			MethodName: "GetFeedbacksByPassengerID",
			Handler:    _CustomerFeedback_GetFeedbacksByPassengerID_Handler,
		},
		{
			MethodName: "GetFeedbackByBookingCode",
			Handler:    _CustomerFeedback_GetFeedbackByBookingCode_Handler,
		},
		{
			MethodName: "DeleteFeedbacksByPassengerID",
			Handler:    _CustomerFeedback_DeleteFeedbacksByPassengerID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedback.proto",
}
